import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();
async function main() {
  console.log("Iniciando seed...");
  await prisma.edital.create({ data: { titulo: "Fomento a Musica Independente", descricao: "Apoio financeiro para artistas musicais independentes desenvolverem projetos autorais e shows.", orgao: "Ministerio da Cultura", valorMaximo: 50000, dataAbertura: new Date("2024-01-01"), dataFechamento: new Date("2026-12-31"), linkOriginal: "https://www.gov.br/cultura", tipo: "BOLSA", status: "ABERTO", nichos: { create: [{ nicho: "MUSICA" }] } } });
  await prisma.edital.create({ data: { titulo: "Premio Nacional de Teatro", descricao: "Premiacao para grupos teatrais com espetaculos ineditos de teatro contemporaneo brasileiro.", orgao: "FUNARTE", valorMaximo: 80000, dataAbertura: new Date("2024-01-01"), dataFechamento: new Date("2026-12-31"), linkOriginal: "https://www.funarte.gov.br", tipo: "PREMIO", status: "ABERTO", nichos: { create: [{ nicho: "TEATRO" }] } } });
  await prisma.edital.create({ data: { titulo: "Residencia Audiovisual e Novas Midias", descricao: "Programa de residencia para cineastas e videoartistas explorarem novas linguagens.", orgao: "Centro Cultural Banco do Brasil", valorMaximo: 30000, dataAbertura: new Date("2024-01-01"), dataFechamento: new Date("2026-12-31"), linkOriginal: "https://www.bb.com.br/cultura", tipo: "RESIDENCIA", status: "ABERTO", nichos: { create: [{ nicho: "AUDIOVISUAL" }] } } });
  await prisma.edital.create({ data: { titulo: "Bolsa Artes Visuais e Danca", descricao: "Bolsas para artistas visuais e bailarinos com projetos que integrem plastica e expressao corporal.", orgao: "Secretaria de Cultura SP", valorMaximo: 25000, dataAbertura: new Date("2024-01-01"), dataFechamento: new Date("2026-12-31"), linkOriginal: "https://www.cultura.sp.gov.br", tipo: "BOLSA", status: "ABERTO", nichos: { create: [{ nicho: "ARTES_VISUAIS" }, { nicho: "DANCA" }] } } });
  await prisma.edital.create({ data: { titulo: "Patrocinio Rouanet Multidisciplinar", descricao: "Captacao via Lei Rouanet para projetos com multiplas linguagens artisticas e impacto social.", orgao: "Ministerio da Cultura", valorMaximo: 200000, dataAbertura: new Date("2024-01-01"), dataFechamento: new Date("2026-12-31"), linkOriginal: "https://www.gov.br/cultura/rouanet", tipo: "PATROCINIO", status: "ABERTO", nichos: { create: [{ nicho: "MUSICA" }, { nicho: "TEATRO" }, { nicho: "AUDIOVISUAL" }, { nicho: "ARTES_VISUAIS" }, { nicho: "DANCA" }] } } });
  await prisma.edital.create({ data: { titulo: "Edital Literatura e Contacao de Historias", descricao: "Apoio para escritores e poetas publicarem obras e realizarem festivais literarios.", orgao: "Biblioteca Nacional", valorMaximo: 15000, dataAbertura: new Date("2024-01-01"), dataFechamento: new Date("2026-12-31"), linkOriginal: "https://www.bn.gov.br", tipo: "BOLSA", status: "ABERTO", nichos: { create: [{ nicho: "LITERATURA" }] } } });
  await prisma.edital.create({ data: { titulo: "Capacitacao em Gestao Cultural", descricao: "Formacao para artistas aprenderem sobre editais, captacao de recursos e empreendedorismo cultural.", orgao: "SESC Nacional", valorMaximo: null, dataAbertura: new Date("2024-01-01"), dataFechamento: new Date("2026-12-31"), linkOriginal: "https://www.sesc.com.br", tipo: "CAPACITACAO", status: "ABERTO", nichos: { create: [{ nicho: "MUSICA" }, { nicho: "TEATRO" }, { nicho: "AUDIOVISUAL" }, { nicho: "LITERATURA" }, { nicho: "CIRCO" }] } } });
  console.log("Seed concluido! 7 editais criados.");
}
main().catch(console.error).finally(() => prisma.$disconnect());
